version: '3'
services:
  decidim:
    image: ghcr.io/decidim/decidim:0.27.0.rc1
    ports:
      - 3000:3000
    volumes:
      # Makes our entrypoint scripts available to the container
      # under /code/vendor
      - ./scripts:/code/vendor
      - app-data:/code/app
      - config-data:/code/config
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
    links:
      - pg
      - redis
    entrypoint: ["/code/vendor/hello-world.sh"]
    # The entrypoint override above wipes out the CMD 
    # on the Dockerfile-deploy, so we need to declare it 
    # again here (https://github.com/docker/compose/issues/3140)
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis
    volumes:
      - redis-data:/data
  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8888:80
    volumes:
        - pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.org
        PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - pg

volumes:
  pg-data: {}
  redis-data: {}
  pgadmin4_data: {}
  app-data: 
    driver_opts:
      type: none
      device: ${PWD}/app
      o: bind
  config-data: 
    driver_opts:
      type: none
      device: ${PWD}/config
      o: bind
